In [90]:
import numpy as np

In [91]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,-2]])

In [92]:
P = np.zeros_like(A)

In [93]:
n = A.shape[0]

In [94]:
for i in range(n):
    for j in range(n):
        for k in range(n):
            P[i,j] += A[i,k]*B[k,j]

In [95]:
print(P)

[[ 4 -2  1]
 [20 -7 12]
 [-8 13 17]]
