In [14]:
import numpy as np

In [15]:
def jacobiano(f, x, h=0.01):
    n = len(x)
    total = np.zeros((n, n))
    
    for i in range(n):
        e = np.zeros(n)
        e[i] = 1
        total[:,i] = (-f(x+2*h*e) + 8*f(x+h*e) - 8*f(x-h*e) + f(x-2*h*e)) / (12*h)
    
    return total

In [16]:
x0 = np.array([0.5, 0.5, 0.5])
J = jacobiano(lambda x: np.array([6*x[0] - 2*np.cos(x[1]*x[2]) - 1,
                                 9*x[1] + np.sqrt(x[0]**2 + np.sin(x[2]) + 1.06) + 0.9,
                                 60*x[2] + 3*np.exp(-x[0]*x[1]) + 10*np.pi - 3]), x0, h=0.01)
print(J)

[[ 6.          0.24740396  0.24740396]
 [ 0.37377753  9.          0.32802064]
 [-1.16820117 -1.16820117 60.        ]]


In [18]:
def derivada_central_2(x, function, h, a):
    sol = function(x + h*a) - function(x - h*a)
    return sol/(2*h)
def jacobiano_4(funciones, derivada, variables, x_point, h):
    n = len(funciones)
    Jacobian = np.zeros((variables, n))
    for i in range(n):
        for j in range(variables):
            a = np.zeros(variables)
            a[j] += 1
            Jacobian[i, j] = derivada(x_point, funciones[i], h, a)

    return Jacobian
def Funcion_1(x):
    return 6*x[0] - 2*np.cos(x[1]*x[2]) - 1

def Funcion_2(x):
    return 9*x[1] + np.sqrt(x[0]**2 + np.sin(x[2]) + 1.06) + 0.9

def Funcion_3(x):
    return 60*x[2] + 3*(np.e**(-x[0]*x[1])) + 10*np.pi - 3

funciones = [Funcion_1, Funcion_2, Funcion_3]

jacobiano_4(funciones, derivada_central_2, 3, np.array([0.5, 0.5, 0.5]), h = 0.0001)

array([[ 6.        ,  0.24740396,  0.24740396],
       [ 0.37377753,  9.        ,  0.32802064],
       [-1.16820118, -1.16820118, 60.        ]])