In [1]:
import numpy as np

In [2]:
A = np.array([[4, -2, 1],
              [20, -7, 12],
              [-8, 13, 17]])
L = np.zeros_like(A)

np.fill_diagonal(L, 1)

U = A.copy()
for i in range(A.shape[0] - 1):
    for j in range(i + 1, A.shape[0]):
        m = U[j, i] / U[i, i]
        U[j, :] = U[j, :] - m * U[i, :]
        L[j, i] = m

print("Matriz L:\n", L)
print("Matriz U:\n", U)

Matriz L:
 [[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]
Matriz U:
 [[ 4 -2  1]
 [ 0  3  7]
 [ 0  0 -2]]
