In [1]:
import numpy as np

In [6]:
def jacobi(A, tol=1e-10, max_iter=1000):
    n = A.shape[0]
    X = np.eye(n)

    for i in range(max_iter):
        diagonal = np.abs(A - np.diag(np.diag(A)))
        
        max_idx = np.unravel_index(np.argmax(diagonal), diagonal.shape)
        if diagonal[max_idx] < tol:
            break

        p, q = max_idx
        theta = 0.5 * np.arctan2(2 * A[p, q], A[q, q] - A[p, p])
        c = np.cos(theta)
        s = np.sin(theta)
        J = np.eye(n)
        J[p, p] = c
        J[q, q] = c
        J[p, q] = s
        J[q, p] = -s

        A = J.T @ A @ J
        X = X @ J

    values = np.diag(A)
    vectors = X
    

    return values, vectors
A = np.array([[4, 1, 1], [1, 3, 2], [1, 2, 5]])
print(jacobi(A))

(array([6.89510652, 3.39729507, 1.70759841]), array([[-0.43170413,  0.88573564,  0.17059871],
       [-0.49725362, -0.07589338, -0.86427949],
       [-0.75257583, -0.45794385,  0.47319874]]))


In [7]:
A = np.array([[4, 1, 1], [1, 3, 2], [1, 2, 5]])
valores, vectores = np.linalg.eig(A)
print(valores,vectores)

[6.89510652 3.39729507 1.70759841] [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]


In [ ]:
#Nos damos cuenta que los resultados son muy parecidos, pues nos dan los mismos númerson en
#mismo orden, sin embargo, hay una diferencia de signos pues de la primera forma nos da 3
#número adicionales con el signo menos.
