In [1]:
import numpy as np

In [8]:

Jx = np.array([[0, 0, 0], [0, 0, -1], [0, 1, 0]])
Jy = np.array([[0, 0, 1], [0, 0, 0], [-1, 0, 0]])
Jz = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 0]])


def conmutador(A, B):
    return np.dot(A, B) - np.dot(B, A)

def levi_civita(i, j, k):
    if i==j or j==k or k==i:
        return 0
    if (i,j,k) in [(1,2,3),(2,3,1),(3,1,2)]:
        return 1
    else:
        return -1


for i, Ji in enumerate([Jx, Jy, Jz]):
    for j, Jj in enumerate([Jx, Jy, Jz]):
        k = [l for l in range(3) if l!=i and l!=j][0]
        con = conmutador(Ji, Jj)
        resultado = levi_civita(i+1, j+1, k+1) * Jz
        if not np.allclose(con, resultado):
            print(f"Error: [{i+1},{j+1}] = {con} no coincide con {resultado}")
print("El álgebra de Lie está dada correctamente.")

Error: [1,3] = [[ 0  0 -1]
 [ 0  0  0]
 [ 1  0  0]] no coincide con [[ 0  1  0]
 [-1  0  0]
 [ 0  0  0]]
Error: [2,3] = [[ 0  0  0]
 [ 0  0 -1]
 [ 0  1  0]] no coincide con [[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  0]]
Error: [3,1] = [[ 0  0  1]
 [ 0  0  0]
 [-1  0  0]] no coincide con [[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  0]]
Error: [3,2] = [[ 0  0  0]
 [ 0  0  1]
 [ 0 -1  0]] no coincide con [[ 0  1  0]
 [-1  0  0]
 [ 0  0  0]]
El álgebra de Lie está dada correctamente.
