In [3]:

import numpy as np

import sympy as sym


In [30]:
def Pesos(n):
    
    pesos =np.polynomial.hermite.hermgauss(n)[1]
    
    return pesos

def Raices(n):
    
    roots =np.polynomial.hermite.hermgauss(n)[0]
    
    return roots

x = np.linspace(-10,10,100)


for i in range(1,21):
    for j in range(1,21):
        print( GetRoots(i) )
        print(GetWeights(j))



[0.]
[1.77245385]
[0.]
[0.88622693 0.88622693]
[0.]
[0.29540898 1.1816359  0.29540898]
[0.]
[0.08131284 0.80491409 0.80491409 0.08131284]
[0.]
[0.01995324 0.39361932 0.94530872 0.39361932 0.01995324]
[0.]
[0.00453001 0.15706732 0.7246296  0.7246296  0.15706732 0.00453001]
[0.]
[0.00097178 0.05451558 0.42560725 0.81026462 0.42560725 0.05451558
 0.00097178]
[0.]
[1.99604072e-04 1.70779830e-02 2.07802326e-01 6.61147013e-01
 6.61147013e-01 2.07802326e-01 1.70779830e-02 1.99604072e-04]
[0.]
[3.96069773e-05 4.94362428e-03 8.84745274e-02 4.32651559e-01
 7.20235216e-01 4.32651559e-01 8.84745274e-02 4.94362428e-03
 3.96069773e-05]
[0.]
[7.64043286e-06 1.34364575e-03 3.38743945e-02 2.40138611e-01
 6.10862634e-01 6.10862634e-01 2.40138611e-01 3.38743945e-02
 1.34364575e-03 7.64043286e-06]
[0.]
[1.43956039e-06 3.46819466e-04 1.19113954e-02 1.17227875e-01
 4.29359752e-01 6.54759287e-01 4.29359752e-01 1.17227875e-01
 1.19113954e-02 3.46819466e-04 1.43956039e-06]
[0.]
[2.65855168e-07 8.57368704e-05 3